# Install

In [ ]:
! pip install lazypredict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Imports

In [ ]:
import pandas as pd
import numpy as np
from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.utils import class_weight

# Data

In [ ]:
dataframe = pd.read_csv('/content/drive/MyDrive/more_features_dataframe_v2.csv')

In [ ]:
dataframe.columns

Index(['line_x_position', 'line_y_position', 'line_x_b_box_x1',
       'line_x_b_box_x2', 'line_x_b_box_y1', 'line_x_b_box_y2',
       'line_y_b_box_x1', 'line_y_b_box_x2', 'line_y_b_box_y1',
       'line_y_b_box_y2', 'width_line_x', 'normalized_width_line_x',
       'width_line_y', 'normalized_width_line_y', 'height_line_x',
       'normalized_height_line_x', 'height_line_y', 'normalized_height_line_y',
       'distance_y_between_lines_x_y',
       'normalized_distance_y_between_lines_x_y',
       'list_distance_y_between_lines_x_y_1',
       'normalized_distance_y_between_lines_x_y_1',
       'distance_x_between_lines_x_y',
       'normalized_distance_x_between_lines_x_y',
       'distance_x_between_lines_x_y_1',
       'normalized_distance_x_between_lines_x_y_1', 'line_x_num_words',
       'line_y_num_words', 'line_x_text', 'line_y_text',
       'mm_normalized_width_line_x', 'mm_normalized_width_line_y',
       'mm_normalized_height_line_x', 'mm_normalized_height_line_y', 'target'],

In [ ]:
print(len(dataframe))
dataframe['target'].value_counts()

4722


1    4041
0     681
Name: target, dtype: int64

In [ ]:
sklearn_weights = class_weight.compute_class_weight(class_weight='balanced',y=dataframe['target'], classes=np.unique(dataframe['target']))
sklearn_weights

array([3.46696035, 0.58426132])

In [ ]:
X = dataframe.drop(columns=['target', 'line_x_text', 'line_y_text'], axis=1)
y = dataframe['target']

# Lazy

In [ ]:
X_train, y_train = X[:3000], y[:3000]

X_test, y_test = X[3000:], y[3000:]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5, random_state =123)

clf = LazyClassifier(verbose=2,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

print(f'\n\n{models}')

  3%|▎         | 1/29 [00:00<00:21,  1.30it/s]

{'Model': 'AdaBoostClassifier', 'Accuracy': 0.9059233449477352, 'Balanced Accuracy': 0.7794055162476214, 'ROC AUC': 0.7794055162476214, 'F1 Score': 0.9020671506473259, 'Time taken': 0.770092248916626}


  7%|▋         | 2/29 [00:01<00:15,  1.69it/s]

{'Model': 'BaggingClassifier', 'Accuracy': 0.9163763066202091, 'Balanced Accuracy': 0.8427518427518428, 'ROC AUC': 0.8427518427518428, 'F1 Score': 0.9168975967234998, 'Time taken': 0.4610011577606201}
{'Model': 'BernoulliNB', 'Accuracy': 0.8948896631823461, 'Balanced Accuracy': 0.7824444403391771, 'ROC AUC': 0.7824444403391771, 'F1 Score': 0.8935904590810709, 'Time taken': 0.05162787437438965}


 21%|██        | 6/29 [00:03<00:12,  1.82it/s]

{'Model': 'CalibratedClassifierCV', 'Accuracy': 0.8734030197444832, 'Balanced Accuracy': 0.5918604865973287, 'ROC AUC': 0.5918604865973287, 'F1 Score': 0.8370277510845944, 'Time taken': 2.3762762546539307}
{'Model': 'DecisionTreeClassifier', 'Accuracy': 0.9018583042973287, 'Balanced Accuracy': 0.8071992019360441, 'ROC AUC': 0.8071992019360441, 'F1 Score': 0.9017801545930667, 'Time taken': 0.09761261940002441}
{'Model': 'DummyClassifier', 'Accuracy': 0.8495934959349594, 'Balanced Accuracy': 0.5, 'ROC AUC': 0.5, 'F1 Score': 0.7805056731886, 'Time taken': 0.02997756004333496}
{'Model': 'ExtraTreeClassifier', 'Accuracy': 0.8600464576074333, 'Balanced Accuracy': 0.7667048456522141, 'ROC AUC': 0.7667048456522141, 'F1 Score': 0.8650772137185725, 'Time taken': 0.05872392654418945}


 31%|███       | 9/29 [00:04<00:07,  2.58it/s]

{'Model': 'ExtraTreesClassifier', 'Accuracy': 0.9442508710801394, 'Balanced Accuracy': 0.875043875043875, 'ROC AUC': 0.875043875043875, 'F1 Score': 0.9433206473502176, 'Time taken': 0.5950417518615723}
{'Model': 'GaussianNB', 'Accuracy': 0.8774680603948897, 'Balanced Accuracy': 0.6705122757754337, 'ROC AUC': 0.6705122757754336, 'F1 Score': 0.862652168403151, 'Time taken': 0.0533597469329834}


 38%|███▊      | 11/29 [00:05<00:06,  2.78it/s]

{'Model': 'KNeighborsClassifier', 'Accuracy': 0.9001161440185831, 'Balanced Accuracy': 0.729914466756572, 'ROC AUC': 0.729914466756572, 'F1 Score': 0.8905985966644621, 'Time taken': 0.5455036163330078}


 41%|████▏     | 12/29 [00:06<00:08,  2.06it/s]

{'Model': 'LabelPropagation', 'Accuracy': 0.9018583042973287, 'Balanced Accuracy': 0.7881343407659197, 'ROC AUC': 0.7881343407659198, 'F1 Score': 0.8997856383117451, 'Time taken': 1.0200300216674805}


 45%|████▍     | 13/29 [00:07<00:11,  1.43it/s]

{'Model': 'LabelSpreading', 'Accuracy': 0.9018583042973287, 'Balanced Accuracy': 0.7881343407659197, 'ROC AUC': 0.7881343407659198, 'F1 Score': 0.8997856383117451, 'Time taken': 1.4782087802886963}


 48%|████▊     | 14/29 [00:07<00:08,  1.71it/s]

{'Model': 'LinearDiscriminantAnalysis', 'Accuracy': 0.8792102206736353, 'Balanced Accuracy': 0.6254641517799412, 'ROC AUC': 0.6254641517799413, 'F1 Score': 0.852051549472734, 'Time taken': 0.1982438564300537}


 52%|█████▏    | 15/29 [00:08<00:08,  1.66it/s]

{'Model': 'LinearSVC', 'Accuracy': 0.8803716608594657, 'Balanced Accuracy': 0.6309138940717889, 'ROC AUC': 0.6309138940717889, 'F1 Score': 0.8544364650409401, 'Time taken': 0.6411049365997314}


 62%|██████▏   | 18/29 [00:08<00:03,  3.16it/s]

{'Model': 'LogisticRegression', 'Accuracy': 0.8803716608594657, 'Balanced Accuracy': 0.6436238015185384, 'ROC AUC': 0.6436238015185383, 'F1 Score': 0.8580563745197891, 'Time taken': 0.22217345237731934}
{'Model': 'NearestCentroid', 'Accuracy': 0.8966318234610917, 'Balanced Accuracy': 0.7326301010511537, 'ROC AUC': 0.7326301010511537, 'F1 Score': 0.8883203627749239, 'Time taken': 0.08599209785461426}
{'Model': 'PassiveAggressiveClassifier', 'Accuracy': 0.8536585365853658, 'Balanced Accuracy': 0.677153571890414, 'ROC AUC': 0.677153571890414, 'F1 Score': 0.8476600121180627, 'Time taken': 0.055239200592041016}


 72%|███████▏  | 21/29 [00:09<00:01,  5.06it/s]

{'Model': 'Perceptron', 'Accuracy': 0.8948896631823461, 'Balanced Accuracy': 0.7427259795680847, 'ROC AUC': 0.742725979568085, 'F1 Score': 0.8884907562832793, 'Time taken': 0.07141661643981934}
{'Model': 'QuadraticDiscriminantAnalysis', 'Accuracy': 0.8623693379790941, 'Balanced Accuracy': 0.5980768875505718, 'ROC AUC': 0.5980768875505718, 'F1 Score': 0.83334367900619, 'Time taken': 0.1045224666595459}


 83%|████████▎ | 24/29 [00:10<00:01,  3.16it/s]

{'Model': 'RandomForestClassifier', 'Accuracy': 0.9314750290360047, 'Balanced Accuracy': 0.8452827400195821, 'ROC AUC': 0.845282740019582, 'F1 Score': 0.9299661797430984, 'Time taken': 1.3996217250823975}
{'Model': 'RidgeClassifier', 'Accuracy': 0.8716608594657376, 'Balanced Accuracy': 0.5940126729600413, 'ROC AUC': 0.5940126729600415, 'F1 Score': 0.8369300295306533, 'Time taken': 0.04553079605102539}
{'Model': 'RidgeClassifierCV', 'Accuracy': 0.8710801393728222, 'Balanced Accuracy': 0.5904934325986958, 'ROC AUC': 0.5904934325986957, 'F1 Score': 0.8352810460322914, 'Time taken': 0.08608174324035645}


 86%|████████▌ | 25/29 [00:10<00:01,  3.59it/s]

{'Model': 'SGDClassifier', 'Accuracy': 0.8797909407665505, 'Balanced Accuracy': 0.6496369917422549, 'ROC AUC': 0.6496369917422549, 'F1 Score': 0.8592637980404176, 'Time taken': 0.1330113410949707}


 90%|████████▉ | 26/29 [00:11<00:01,  2.89it/s]

{'Model': 'SVC', 'Accuracy': 0.9204413472706156, 'Balanced Accuracy': 0.7482311429679851, 'ROC AUC': 0.7482311429679851, 'F1 Score': 0.9098968541540938, 'Time taken': 0.545806884765625}


 97%|█████████▋| 28/29 [00:12<00:00,  2.39it/s]

{'Model': 'XGBClassifier', 'Accuracy': 0.9198606271777003, 'Balanced Accuracy': 0.7907853171011066, 'ROC AUC': 0.7907853171011066, 'F1 Score': 0.9148936339051053, 'Time taken': 1.0214412212371826}


100%|██████████| 29/29 [00:13<00:00,  2.18it/s]

{'Model': 'LGBMClassifier', 'Accuracy': 0.9465737514518002, 'Balanced Accuracy': 0.892298313350945, 'ROC AUC': 0.892298313350945, 'F1 Score': 0.9464023356452471, 'Time taken': 0.8914453983306885}


                               Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
LGBMClassifier                     0.95               0.89     0.89      0.95   
ExtraTreesClassifier               0.94               0.88     0.88      0.94   
RandomForestClassifier             0.93               0.85     0.85      0.93   
BaggingClassifier                  0.92               0.84     0.84      0.92   
DecisionTreeClassifier             0.90               0.81     0.81      0.90   
XGBClassifier                      0.92               0.79     0.79      0.91   
LabelPropagation                   0.90               0.79     0.79      0.90   
LabelSpreading                     0.90               0.79     0.79      

# grid random trees

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
def evaluate_model(dt_classifier,x_train, x_test, y_train, y_test):
    print("Train Accuracy :", accuracy_score(y_train, dt_classifier.predict(x_train)))
    print("Train Confusion Matrix:")
    print(confusion_matrix(y_train, dt_classifier.predict(x_train), labels=[1,0]))
    print("-"*50)
    print("Test Accuracy :", accuracy_score(y_test, dt_classifier.predict(x_test)))
    print("Test Confusion Matrix:")
    print(confusion_matrix(y_test, dt_classifier.predict(x_test), labels=[1,0]))

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': range(1,5),
    'min_samples_leaf': range(1,5),
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}# Create a based model

rf = RandomForestClassifier(random_state=42, class_weight={0:sklearn_weights[0], 1:sklearn_weights[1]})

# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 4, n_jobs = -1, verbose = 2, scoring = "accuracy")

In [ ]:
grid_search.fit(X, y)

Fitting 4 folds for each of 768 candidates, totalling 3072 fits


GridSearchCV(cv=4,
             estimator=RandomForestClassifier(class_weight={0: 3.4669603524229076,
                                                            1: 0.5842613214550854},
                                              random_state=42),
             n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [80, 90, 100, 110],
                         'max_features': range(1, 5),
                         'min_samples_leaf': range(1, 5),
                         'min_samples_split': [8, 10, 12],
                         'n_estimators': [100, 200, 300, 1000]},
             scoring='accuracy', verbose=2)

In [ ]:
grid_search.best_estimator_

RandomForestClassifier(class_weight={0: 3.4669603524229076,
                                     1: 0.5842613214550854},
                       max_depth=80, max_features=1, min_samples_split=8,
                       random_state=42)

In [ ]:
"""
RandomForestClassifier(class_weight={0: 3.4669603524229076,
                                     1: 0.5842613214550854},
                       max_depth=80, max_features=1, min_samples_split=8,
                       random_state=42)
"""
dt_best = grid_search.best_estimator_

In [ ]:
evaluate_model(dt_best, X_train, X_test, y_train, y_test)

Train Accuracy : 0.9983333333333333
Train Confusion Matrix:
[[2575    3]
 [   2  420]]
--------------------------------------------------
Test Accuracy : 0.9976771196283392
Test Confusion Matrix:
[[1459    4]
 [   0  259]]


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, dt_best.predict(x_test)))

NameError: ignored

In [ ]:
import pickle

with open('grid_random_forest_without_embedding_v2_no_sub_label.pkl','wb') as f:
  pickle.dump(dt_best,f)

# Train Val TEst

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load the iris dataset
iris = load_iris()

# Split the data into train, validation, and test sets
X_train_val, X_test, y_train_val, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42)

# Build a logistic regression model
model = LogisticRegression(random_state=42)

# Train the model on the training set
model.fit(X_train, y_train)

# Evaluate the model on the validation set
y_val_pred = model.predict(X_val)
val_accuracy = accuracy_score(y_val, y_val_pred)
print("Validation accuracy:", val_accuracy)

# Evaluate the model on the test set
y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Test accuracy:", test_accuracy)
